### ISSUE TITLE
Single digit integer is being picked up as a CharField

### ISSUE THREAD

**Issue by Fuzzwah** [PSteph/jsonToOrmMapper#2]
I'm mapping example json to Django models. I've got fields in my example json that include things like:

```
"car_id": 1,
```

These `_id` fields are being mapped to CharField:

```
car_id = models.CharField(max_length=100)
```

https://github.com/PSteph/jsonToOrmMapper/blob/09df77e421d6b6ddaba61da584769eb815e9c859/src/main/java/com/p2sdev/jsonToOrmMapper/convert/MapJsonToTable.java#L99

I'm not a java guy, but I think the problem is that the line above is being run before the `Integer.parseInt(data);`

My work around has just to be to search replace all the entries in my example to make the integers at least 2 digits.

**Comment by PSteph** [comment]
Thank you for reporting that issue. It is now solved 😊
